# Generated by Django 5.1 on 2025-08-01 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitBills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='bill_member',
            new_name='payed_by',
        ),
        migrations.AddField(
            model_name='bill',
            name='payed_for',
            field=models.ManyToManyField(blank=True, related_name='bills_payed_for', to='splitBills.billgroupmember'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payed_for_everyone',
            field=models.BooleanField(default=False, help_text='If true, the bill is payed for everyone in the bill group (including the payer)'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('payed_by', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='billgroup',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='billgroupmember',
            unique_together={('bill_group', 'name')},
        ),
    ]
