# Generated by Django 5.1 on 2025-08-04 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitBills', '0002_rename_bill_member_bill_payed_by_bill_payed_for_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='splitBills.billgroup'),
        ),
        migrations.AlterField(
            model_name='billgroupmember',
            name='bill_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_group_members', to='splitBills.billgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('payed_by', 'description', 'bill_group')},
        ),
    ]
